name: TitleX
main: io.github.hhui64.titlex.TitleX
version: 0.0.1
authors: [Netherfoam, Timtower, KaiNoMood, hhui64]

description: Title plugin
softdepend: [Essentials, Vault]

commands:
    ttx:
        description: TitleX command
        usage: /ttx
        aliases: [titlex]
        
permissions:
    titlex.use:
        description: use
        default: true